name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  http: ^0.13.6
  network_repository:
    path: ../network_repository
  uuid: ^3.0.0

dev_dependencies:
  very_good_analysis: ^3.1.0
