apiVersion: apps/v1
kind: Deployment
metadata:
  name: sagile-mobile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sagile-mobile
  template:
    metadata:
      labels:
        app: sagile-mobile
    spec:
      containers:
      - name: sagile-mobile
        image: harisazhr/sagilemobile
        ports:
        - containerPort: 2376
